### ISSUE TITLE
Print more meaningful error messages (use of `pydantic.ValidationError.json()`)

### ISSUE THREAD

**Issue by dawidp** [livioribeiro/frontman#1]
I would suggest use of of `pydantic.ValidationError.json()` as it displays quite nice and more detailed error message, something like this:

    PS C:\Projekty\python\frontman_test> pipenv run frontman install
    Error: Manifest is not in expected format
    [
      {
        "loc": [
          "provider"
        ],
        "msg": "value is not a valid enumeration member; permitted: 'cdnjs', 'jsdelivr', 'unpkg'",
        "type": "type_error.enum",
        "ctx": {
          "enum_values": [
            "cdnjs",
            "jsdelivr",
            "unpkg"
          ]
        }
      }
    ]

is more readable and gives location of the error better than this message:

    PS C:\Projekty\python\frontman_test> pipenv run frontman install
    Error: Manifest is not in expected format

which says that something went wrong not explaining what. And the code change is very simple:

https://github.com/livioribeiro/frontman/blob/521c4e4424e79e613d5c33be004cd2012fddb89c/src/frontman/main.py#L106-L108

``` python
    except pydantic.ValidationError as e:
        typer.echo("Error: Manifest is not in expected format", err=True)
        typer.echo(e.json(), err=True)
        raise typer.Exit(code=1)
```

**Comment by livioribeiro** [comment]
I am sorry it took so long, I'm adding this right now
